Repository CodersCrew/coders-card, pull requests merged in 2021-04, with the labels that each got.

#177 Update project dependencies
  .eslintrc.js
  .storybook/main.js
  gatsby-browser.js
  gatsby-config.js
  gatsby-ssr.js
  package.json
  src/views/blog/Blog.query.ts
  yarn.lock
Labels: maintenance

#178 Remove blog page from the project
  .zeplin/components.json
  content/blog/background.jpg
  content/blog/image.jpg
  content/blog/index.md
  docs/images/about-collection.png
  docs/images/blog-collection.png
  docs/images/cms-view.png
  docs/images/up-and-running.png
  docs/setup-guide.md
  gatsby-node.js
  src/components/BlogPost/BlogPost.stories.tsx
  src/components/BlogPost/BlogPost.tsx
  src/components/BlogPost/index.ts
  src/components/BlogPostDialog/BlogPostDialog.stories.tsx
  src/components/BlogPostDialog/BlogPostDialog.tsx
  src/components/BlogPostDialog/BlogPostDialog.types.ts
  src/components/BlogPostDialog/BlogPostDialogDesktop.tsx
  src/components/BlogPostDialog/BlogPostDialogMobile.tsx
  src/components/BlogPostDialog/BlogPostDialogTablet.tsx
  src/components/BlogPostDialog/index.ts
  src/components/Navbar/Navbar.stories.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/NavbarDesktop.tsx
  src/components/Navbar/NavbarMobile.tsx
  src/components/Navbar/NavbarTablet.tsx
  src/components/Navbar/renderNavItems.tsx
  src/pages/blog.tsx
  src/views/blog/Blog.query.ts
  src/views/blog/Blog.styles.ts
  src/views/blog/Blog.tsx
  src/views/blog/index.ts
  static/admin/config.yml
Labels: config, docs, maintenance

#181 Adapt DeveloperProfile card to match its mockups
  src/components/DetailsCard/DetailsCardDesktop.tsx
Labels: bug, maintenance

#183 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: docs

#170 (#166) Bunch of fixes
  src/components/Button/Button.tsx
  src/components/Testimonial/TestimonialDefault.tsx
  src/components/TestimonialsSection/TestimonialsSection.tsx
Labels: bug, maintenance
